tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "buo/cask-upgrade"
tap "homebrew/cask-fonts"
tap "tigerstrikemedia/phalconphp"

# brew
brew "github-keygen"
brew "mas"
brew "gh"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python"
brew "node"

# cask
cask "visual-studio-code"
cask "alacritty"
cask "warp"
cask "firefox"
cask "google-chrome"

# mas
mas "Xcode", id: 497799835

# brew "gnupg"
# brew "pinentry-mac"
# brew "stow"
# cask "atom"
# cask "carbon-copy-cloner"cask "atom"
# cask "typora"
